; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200

; Libraries
lib_deps =
    mfrc522
    TFT_eSPI
    ArduinoJson

; Build flags
build_flags =
    -DUSER_SETUP_LOADED=1
    -DST7735_DRIVER=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DST7735_GREENTAB=1
    -DSPI_FREQUENCY=27000000
    -DSPI_READ_FREQUENCY=20000000

; Upload settings
upload_speed = 921600