"""baseline schema

Revision ID: 4c977f1467d9
Revises: 
Create Date: 2026-07-04 01:36:17.596533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c977f1467d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'CREATE', 'READ', 'UPDATE', 'DELETE', 'TRANSACTION', 'REFUND', 'CONFIG_CHANGE', 'FAILED_LOGIN', name='audit_action'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_date', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('balance_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('snapshot_type', sa.String(length=50), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('total_additions', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_deductions', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_refunds', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_card_date', 'balance_snapshots', ['card_uid', 'snapshot_at'], unique=False)
    op.create_index('idx_snapshots_company_type', 'balance_snapshots', ['company_id', 'snapshot_type', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_card_uid'), 'balance_snapshots', ['card_uid'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_company_id'), 'balance_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_balance_snapshots_snapshot_at'), 'balance_snapshots', ['snapshot_at'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('card_type', sa.Enum('REGULAR', 'VIP', 'STAFF', 'TEST', name='card_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOST', 'STOLEN', 'DAMAGED', name='card_status'), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cards_owner_status', 'cards', ['owner', 'status'], unique=False)
    op.create_index('idx_cards_type_status', 'cards', ['card_type', 'status'], unique=False)
    op.create_index('idx_cards_uid_type', 'cards', ['card_uid', 'card_type'], unique=False)
    op.create_index(op.f('ix_cards_card_type'), 'cards', ['card_type'], unique=False)
    op.create_index(op.f('ix_cards_card_uid'), 'cards', ['card_uid'], unique=True)
    op.create_index(op.f('ix_cards_company_id'), 'cards', ['company_id'], unique=False)
    op.create_index(op.f('ix_cards_status'), 'cards', ['status'], unique=False)
    op.create_table('charge_idempotency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_txn_id', sa.String(length=255), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('server_txn_id', sa.String(length=255), nullable=False),
    sa.Column('balance_after_cents', sa.BigInteger(), nullable=True),
    sa.Column('price_cents', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_idempotency_card_uid'), 'charge_idempotency', ['card_uid'], unique=False)
    op.create_index(op.f('ix_charge_idempotency_client_txn_id'), 'charge_idempotency', ['client_txn_id'], unique=False)
    op.create_index(op.f('ix_charge_idempotency_company_id'), 'charge_idempotency', ['company_id'], unique=False)
    op.create_index(op.f('ix_charge_idempotency_created_at'), 'charge_idempotency', ['created_at'], unique=False)
    op.create_index(op.f('ix_charge_idempotency_device_id'), 'charge_idempotency', ['device_id'], unique=False)
    op.create_index('uq_charge_idem_company_client', 'charge_idempotency', ['company_id', 'client_txn_id'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('max_venues', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_companies_name', 'companies', ['name'], unique=False)
    op.create_index('idx_companies_slug', 'companies', ['slug'], unique=False)
    op.create_index('idx_companies_status', 'companies', ['status'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_visit', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_email', 'customers', ['email'], unique=False)
    op.create_index('idx_customers_name', 'customers', ['first_name', 'last_name'], unique=False)
    op.create_index('idx_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_user_id'), 'customers', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('device_token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'INACTIVE', name='device_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_devices_company_status', 'devices', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_devices_company_id'), 'devices', ['company_id'], unique=False)
    op.create_index(op.f('ix_devices_device_token_hash'), 'devices', ['device_token_hash'], unique=True)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_table('house_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_accounts_account_type'), 'house_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_house_accounts_company_id'), 'house_accounts', ['company_id'], unique=False)
    op.create_index('uq_house_account_company_type', 'house_accounts', ['company_id', 'account_type'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('opens_at', sa.String(length=10), nullable=True),
    sa.Column('closes_at', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_city', 'locations', ['city'], unique=False)
    op.create_index('idx_locations_name', 'locations', ['name'], unique=False)
    op.create_index('idx_locations_region', 'locations', ['region_id'], unique=False)
    op.create_index('idx_locations_status', 'locations', ['status'], unique=False)
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index(op.f('ix_locations_company_id'), 'locations', ['company_id'], unique=False)
    op.create_index(op.f('ix_locations_manager_id'), 'locations', ['manager_id'], unique=False)
    op.create_index(op.f('ix_locations_region_id'), 'locations', ['region_id'], unique=False)
    op.create_index(op.f('ix_locations_status'), 'locations', ['status'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('machine_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cost_per_play', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('revenue_total', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('revenue_today', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('plays_today', sa.String(length=50), nullable=False),
    sa.Column('total_plays', sa.String(length=50), nullable=False),
    sa.Column('last_played', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maintenance_notes', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('idx_machines_code', 'machines', ['code'], unique=False)
    op.create_index('idx_machines_location', 'machines', ['location_id'], unique=False)
    op.create_index('idx_machines_status', 'machines', ['status'], unique=False)
    op.create_index('idx_machines_type', 'machines', ['machine_type'], unique=False)
    op.create_index(op.f('ix_machines_code'), 'machines', ['code'], unique=True)
    op.create_index(op.f('ix_machines_location_id'), 'machines', ['location_id'], unique=False)
    op.create_index(op.f('ix_machines_machine_type'), 'machines', ['machine_type'], unique=False)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    op.create_table('refresh_token_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('revocation_reason', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_blacklist_expires_at', 'refresh_token_blacklist', ['expires_at'], unique=False)
    op.create_index('idx_refresh_blacklist_token_hash', 'refresh_token_blacklist', ['token_hash'], unique=False)
    op.create_index('idx_refresh_blacklist_user_id', 'refresh_token_blacklist', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_blacklist_expires_at'), 'refresh_token_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_token_blacklist_token_hash'), 'refresh_token_blacklist', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_blacklist_user_id'), 'refresh_token_blacklist', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('STAFF', 'SUPERVISOR', 'REGIONAL_MGR', 'ADMIN', 'OWNER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING', name='user_status'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('backup_codes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_lower', 'users', ['email'], unique=False)
    op.create_index('idx_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_index('idx_users_status_active', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('offline_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_offline_tokens_card_active', 'offline_tokens', ['card_uid', 'is_revoked'], unique=False)
    op.create_index('idx_offline_tokens_device_active', 'offline_tokens', ['device_id', 'is_revoked'], unique=False)
    op.create_index('idx_offline_tokens_expiry', 'offline_tokens', ['expires_at', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_offline_tokens_card_uid'), 'offline_tokens', ['card_uid'], unique=False)
    op.create_index(op.f('ix_offline_tokens_company_id'), 'offline_tokens', ['company_id'], unique=False)
    op.create_index(op.f('ix_offline_tokens_device_id'), 'offline_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_offline_tokens_expires_at'), 'offline_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_offline_tokens_issued_at'), 'offline_tokens', ['issued_at'], unique=False)
    op.create_index(op.f('ix_offline_tokens_token_id'), 'offline_tokens', ['token_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_card_date', 'transactions', ['card_uid', 'created_at'], unique=False)
    op.create_index('idx_transactions_type_date', 'transactions', ['transaction_type', 'created_at'], unique=False)
    op.create_index('idx_transactions_user_date', 'transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_card_uid'), 'transactions', ['card_uid'], unique=False)
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('balance_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('balance_before', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ledger_card_date', 'balance_ledger', ['card_uid', 'created_at', 'operation_type'], unique=False)
    op.create_index('idx_ledger_company_date', 'balance_ledger', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_ledger_reason_code', 'balance_ledger', ['reason_code'], unique=False)
    op.create_index('idx_ledger_transaction', 'balance_ledger', ['transaction_id'], unique=False)
    op.create_index('idx_ledger_user_date', 'balance_ledger', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_balance_ledger_card_uid'), 'balance_ledger', ['card_uid'], unique=False)
    op.create_index(op.f('ix_balance_ledger_company_id'), 'balance_ledger', ['company_id'], unique=False)
    op.create_index(op.f('ix_balance_ledger_created_at'), 'balance_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_balance_ledger_transaction_id'), 'balance_ledger', ['transaction_id'], unique=False)
    op.create_table('offline_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_uid', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('offline_token_id', sa.String(length=255), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=True),
    sa.Column('location_id', sa.String(length=255), nullable=True),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('server_transaction_id', sa.UUID(), nullable=True),
    sa.Column('device_signature', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_offline_tx_company_pending', 'offline_transactions', ['company_id', 'sync_status'], unique=False)
    op.create_index('idx_offline_tx_device_pending', 'offline_transactions', ['device_id', 'sync_status'], unique=False)
    op.create_index('idx_offline_tx_sync_status', 'offline_transactions', ['sync_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_offline_transactions_card_uid'), 'offline_transactions', ['card_uid'], unique=False)
    op.create_index(op.f('ix_offline_transactions_company_id'), 'offline_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_offline_transactions_created_at'), 'offline_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_offline_transactions_device_id'), 'offline_transactions', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offline_transactions_device_id'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_created_at'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_company_id'), table_name='offline_transactions')
    op.drop_index(op.f('ix_offline_transactions_card_uid'), table_name='offline_transactions')
    op.drop_index('idx_offline_tx_sync_status', table_name='offline_transactions')
    op.drop_index('idx_offline_tx_device_pending', table_name='offline_transactions')
    op.drop_index('idx_offline_tx_company_pending', table_name='offline_transactions')
    op.drop_table('offline_transactions')
    op.drop_index(op.f('ix_balance_ledger_transaction_id'), table_name='balance_ledger')
    op.drop_index(op.f('ix_balance_ledger_created_at'), table_name='balance_ledger')
    op.drop_index(op.f('ix_balance_ledger_company_id'), table_name='balance_ledger')
    op.drop_index(op.f('ix_balance_ledger_card_uid'), table_name='balance_ledger')
    op.drop_index('idx_ledger_user_date', table_name='balance_ledger')
    op.drop_index('idx_ledger_transaction', table_name='balance_ledger')
    op.drop_index('idx_ledger_reason_code', table_name='balance_ledger')
    op.drop_index('idx_ledger_company_date', table_name='balance_ledger')
    op.drop_index('idx_ledger_card_date', table_name='balance_ledger')
    op.drop_table('balance_ledger')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_card_uid'), table_name='transactions')
    op.drop_index('idx_transactions_user_date', table_name='transactions')
    op.drop_index('idx_transactions_type_date', table_name='transactions')
    op.drop_index('idx_transactions_card_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_offline_tokens_token_id'), table_name='offline_tokens')
    op.drop_index(op.f('ix_offline_tokens_issued_at'), table_name='offline_tokens')
    op.drop_index(op.f('ix_offline_tokens_expires_at'), table_name='offline_tokens')
    op.drop_index(op.f('ix_offline_tokens_device_id'), table_name='offline_tokens')
    op.drop_index(op.f('ix_offline_tokens_company_id'), table_name='offline_tokens')
    op.drop_index(op.f('ix_offline_tokens_card_uid'), table_name='offline_tokens')
    op.drop_index('idx_offline_tokens_expiry', table_name='offline_tokens')
    op.drop_index('idx_offline_tokens_device_active', table_name='offline_tokens')
    op.drop_index('idx_offline_tokens_card_active', table_name='offline_tokens')
    op.drop_table('offline_tokens')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index('idx_users_status_active', table_name='users')
    op.drop_index('idx_users_role_status', table_name='users')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_token_blacklist_user_id'), table_name='refresh_token_blacklist')
    op.drop_index(op.f('ix_refresh_token_blacklist_token_hash'), table_name='refresh_token_blacklist')
    op.drop_index(op.f('ix_refresh_token_blacklist_expires_at'), table_name='refresh_token_blacklist')
    op.drop_index('idx_refresh_blacklist_user_id', table_name='refresh_token_blacklist')
    op.drop_index('idx_refresh_blacklist_token_hash', table_name='refresh_token_blacklist')
    op.drop_index('idx_refresh_blacklist_expires_at', table_name='refresh_token_blacklist')
    op.drop_table('refresh_token_blacklist')
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_machine_type'), table_name='machines')
    op.drop_index(op.f('ix_machines_location_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_code'), table_name='machines')
    op.drop_index('idx_machines_type', table_name='machines')
    op.drop_index('idx_machines_status', table_name='machines')
    op.drop_index('idx_machines_location', table_name='machines')
    op.drop_index('idx_machines_code', table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_locations_status'), table_name='locations')
    op.drop_index(op.f('ix_locations_region_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_manager_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_company_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.drop_index('idx_locations_status', table_name='locations')
    op.drop_index('idx_locations_region', table_name='locations')
    op.drop_index('idx_locations_name', table_name='locations')
    op.drop_index('idx_locations_city', table_name='locations')
    op.drop_table('locations')
    op.drop_index('uq_house_account_company_type', table_name='house_accounts')
    op.drop_index(op.f('ix_house_accounts_company_id'), table_name='house_accounts')
    op.drop_index(op.f('ix_house_accounts_account_type'), table_name='house_accounts')
    op.drop_table('house_accounts')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_token_hash'), table_name='devices')
    op.drop_index(op.f('ix_devices_company_id'), table_name='devices')
    op.drop_index('idx_devices_company_status', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_customers_user_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index('idx_customers_phone', table_name='customers')
    op.drop_index('idx_customers_name', table_name='customers')
    op.drop_index('idx_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index('idx_companies_status', table_name='companies')
    op.drop_index('idx_companies_slug', table_name='companies')
    op.drop_index('idx_companies_name', table_name='companies')
    op.drop_table('companies')
    op.drop_index('uq_charge_idem_company_client', table_name='charge_idempotency')
    op.drop_index(op.f('ix_charge_idempotency_device_id'), table_name='charge_idempotency')
    op.drop_index(op.f('ix_charge_idempotency_created_at'), table_name='charge_idempotency')
    op.drop_index(op.f('ix_charge_idempotency_company_id'), table_name='charge_idempotency')
    op.drop_index(op.f('ix_charge_idempotency_client_txn_id'), table_name='charge_idempotency')
    op.drop_index(op.f('ix_charge_idempotency_card_uid'), table_name='charge_idempotency')
    op.drop_table('charge_idempotency')
    op.drop_index(op.f('ix_cards_status'), table_name='cards')
    op.drop_index(op.f('ix_cards_company_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_uid'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_type'), table_name='cards')
    op.drop_index('idx_cards_uid_type', table_name='cards')
    op.drop_index('idx_cards_type_status', table_name='cards')
    op.drop_index('idx_cards_owner_status', table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_balance_snapshots_snapshot_at'), table_name='balance_snapshots')
    op.drop_index(op.f('ix_balance_snapshots_company_id'), table_name='balance_snapshots')
    op.drop_index(op.f('ix_balance_snapshots_card_uid'), table_name='balance_snapshots')
    op.drop_index('idx_snapshots_company_type', table_name='balance_snapshots')
    op.drop_index('idx_snapshots_card_date', table_name='balance_snapshots')
    op.drop_table('balance_snapshots')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_date', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
