// =============================================================================
// net_client.h  --  HTTPS transport for the money path
// =============================================================================
// Wraps WiFiClientSecure + HTTPClient. Every request carries
//   Authorization: Bearer <device_token>
// and (in production) validates the server against the pinned root CA.
//
// Endpoints (server contract):
//   POST /api/v1/charge
//   GET  /api/v1/devices/{id}/offline-envelope
//   POST /api/v1/reconcile
// =============================================================================
#pragma once

#include <Arduino.h>
#include "config.h"

// Result of a charge attempt.
struct ChargeOutcome {
    enum Status { Approved, Declined, NetworkError, ProtocolError } status = NetworkError;
    int64_t balanceAfterCents = -1;
    String  serverTxnId;
    int     httpCode = 0;
    String  rawBody;   // for logging/diagnostics
};

namespace net {

// Provide config (base url, token, device id). Call once after configLoad().
void begin(const DeviceConfig& cfg);

// Bring up WiFi (blocking up to TC_WIFI_CONNECT_TIMEOUT_MS). Returns connected.
bool wifiConnect();
bool wifiConnected();

// ---- Money path ------------------------------------------------------------

// POST /api/v1/charge. Builds the request body from the given fields, retries
// idempotently (same client_txn_id) on transient network errors. `nonce`/`ts`
// are generated by the caller so a retry reuses the SAME client_txn_id but may
// refresh nonce/ts per the contract.
ChargeOutcome charge(const String& cardUid, uint32_t priceCents,
                     const String& sku, const String& clientTxnId,
                     uint64_t tsEpoch);

// GET /api/v1/devices/{id}/offline-envelope. On HTTP 200, returns the raw JSON
// body in `outBody` (caller passes it to offline::storeEnvelopeFromJson to
// verify + cache). Returns the HTTP status code (or <0 on transport failure).
int fetchOfflineEnvelope(String& outBody);

// POST /api/v1/reconcile with a pre-serialized batch body. Returns HTTP code
// (200/2xx = accepted). Body echoed into `outBody` for diagnostics.
int reconcile(const String& batchJson, String& outBody);

}  // namespace net
